# generated by datamodel-codegen:
#   filename:  input.schema.yaml
#   timestamp: 2025-03-30T19:20:33+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field


class Company(BaseModel):
    field_ref: str = Field(..., alias='$ref')


class Stock(BaseModel):
    field_ref: str = Field(..., alias='$ref')


class Properties(BaseModel):
    company: Company
    stock: Stock


class Model(BaseModel):
    type: str
    properties: Properties
    required: List[str]
