# generated by datamodel-codegen:
#   filename:  output.schema.yaml
#   timestamp: 2025-03-30T19:49:12+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field


class Summary(BaseModel):
    field_ref: str = Field(..., alias='$ref')


class AdditionalNotes(BaseModel):
    type: str


class Properties(BaseModel):
    summary: Summary
    additional_notes: AdditionalNotes


class Model(BaseModel):
    type: str
    properties: Properties
    required: List[str]
