service: prompt-manager-lambda
frameworkVersion: '2'
provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
functions:
  promptHandler:
    handler: dist/lambda.handler
    events:
      - http:
          path: prompt
          method: post
