service: prompt-manager-lambda
provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
functions:
  promptHandler:
    handler: src/lambda.handler
    url: true
    events:
      - http:
          path: prompt
          method: post
package:
  patterns:
    - "src/**"
    - "node_modules/**"
    - "package.json"
    - "schemas/**"
    - "templates/**"
