# generated by datamodel-codegen:
#   filename:  input.schema.yaml
#   timestamp: 2025-03-30T19:20:30+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field


class Company(BaseModel):
    field_ref: str = Field(..., alias='$ref')


class Market(BaseModel):
    field_ref: str = Field(..., alias='$ref')


class Historical(BaseModel):
    field_ref: str = Field(..., alias='$ref')


class Properties(BaseModel):
    company: Company
    market: Market
    historical: Historical


class Model(BaseModel):
    type: str
    properties: Properties
    required: List[str]
