# generated by datamodel-codegen:
#   filename:  output.schema.yaml
#   timestamp: 2025-03-30T19:20:30+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field


class Analysis(BaseModel):
    field_ref: str = Field(..., alias='$ref')


class Comments(BaseModel):
    type: str


class Properties(BaseModel):
    analysis: Analysis
    comments: Comments


class Model(BaseModel):
    type: str
    properties: Properties
    required: List[str]
