# generated by datamodel-codegen:
#   filename:  company.schema.yaml
#   timestamp: 2025-03-30T19:20:32+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class Name(BaseModel):
    type: str


class Industry(BaseModel):
    type: str


class Ceo(BaseModel):
    type: str


class Revenue(BaseModel):
    type: str


class Profit(BaseModel):
    type: str


class Eps(BaseModel):
    type: str


class PeRatio(BaseModel):
    type: str


class PbRatio(BaseModel):
    type: str


class Properties1(BaseModel):
    revenue: Revenue
    profit: Profit
    eps: Eps
    pe_ratio: PeRatio
    pb_ratio: PbRatio


class Financials(BaseModel):
    type: str
    properties: Properties1
    required: List[str]


class Properties(BaseModel):
    name: Name
    industry: Industry
    ceo: Ceo
    financials: Financials


class Model(BaseModel):
    type: str
    properties: Properties
    required: List[str]
