# generated by datamodel-codegen:
#   filename:  historical.schema.yaml
#   timestamp: 2025-03-30T19:20:32+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class LastClose(BaseModel):
    type: str


class High(BaseModel):
    type: str


class Low(BaseModel):
    type: str


class Properties(BaseModel):
    last_close: LastClose
    high: High
    low: Low


class Model(BaseModel):
    type: str
    properties: Properties
    required: List[str]
