# generated by datamodel-codegen:
#   filename:  market.schema.yaml
#   timestamp: 2025-03-30T19:20:32+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class SectorGrowth(BaseModel):
    type: str


class Items(BaseModel):
    type: str


class Trends(BaseModel):
    type: str
    items: Items


class Properties(BaseModel):
    sector_growth: SectorGrowth
    trends: Trends


class Model(BaseModel):
    type: str
    properties: Properties
    required: List[str]
