# generated by datamodel-codegen:
#   filename:  stock.schema.yaml
#   timestamp: 2025-03-30T19:20:31+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class CurrentPrice(BaseModel):
    type: str


class Volume(BaseModel):
    type: str


class Sentiment(BaseModel):
    type: str


class Properties(BaseModel):
    current_price: CurrentPrice
    volume: Volume
    sentiment: Sentiment


class Model(BaseModel):
    type: str
    properties: Properties
    required: List[str]
