# generated by datamodel-codegen:
#   filename:  merged_entities.yaml
#   timestamp: 2025-03-30T19:49:09+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field


class Ceo(BaseModel):
    type: str


class Eps(Ceo):
    pass


class PbRatio(Ceo):
    pass


class PeRatio(Ceo):
    pass


class Profit(Ceo):
    pass


class Revenue(Ceo):
    pass


class Properties1(BaseModel):
    eps: Eps
    pb_ratio: PbRatio
    pe_ratio: PeRatio
    profit: Profit
    revenue: Revenue


class Financials(BaseModel):
    properties: Properties1
    required: List[str]
    type: str


class Industry(Ceo):
    pass


class Name(Ceo):
    pass


class Properties(BaseModel):
    ceo: Ceo
    financials: Financials
    industry: Industry
    name: Name


class CompanySchema(BaseModel):
    properties: Properties
    required: List[str]
    type: str


class High(Ceo):
    pass


class LastClose(Ceo):
    pass


class Low(Ceo):
    pass


class Properties2(BaseModel):
    high: High
    last_close: LastClose
    low: Low


class HistoricalSchema(BaseModel):
    properties: Properties2
    required: List[str]
    type: str


class SectorGrowth(Ceo):
    pass


class Items(Ceo):
    pass


class Trends(BaseModel):
    items: Items
    type: str


class Properties3(BaseModel):
    sector_growth: SectorGrowth
    trends: Trends


class MarketSchema(BaseModel):
    properties: Properties3
    required: List[str]
    type: str


class CurrentPrice(Ceo):
    pass


class Sentiment(Ceo):
    pass


class Volume(Ceo):
    pass


class Properties4(BaseModel):
    current_price: CurrentPrice
    sentiment: Sentiment
    volume: Volume


class StockSchema(BaseModel):
    properties: Properties4
    required: List[str]
    type: str


class FieldDefs(BaseModel):
    company_schema: CompanySchema = Field(..., alias='company.schema')
    historical_schema: HistoricalSchema = Field(..., alias='historical.schema')
    market_schema: MarketSchema = Field(..., alias='market.schema')
    stock_schema: StockSchema = Field(..., alias='stock.schema')


class Model(BaseModel):
    field_defs: FieldDefs = Field(..., alias='$defs')
    field_schema: str = Field(..., alias='$schema')
